# Generated by Django 5.2 on 2025-05-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('rentals', '0002_rental_invoice_generated_rental_is_paid'),
        ('subscriptions', '0002_subscription_invoice_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
    ]
