# Generated by Django 5.2 on 2025-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_invoice_generated_rental_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
