# Generated by Django 5.2 on 2025-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
    ]
